version: '3.9'
name: corretto-assessment
services:
  app:
    image: $DOCKER_REPO:latest
    restart: on-failure
    ports:
      - '80:8080'
    environment:
      - PORT=8080
      - DATABASE_URL=$DATABASE_URL
